### ISSUE TITLE
Could not match name 'M' with HTMLFormStructure

### ISSUE THREAD

**Issue by troystaylor** [ZanattaMichael/SelMVP#64]
I am seeing this error when using the following in a CSV file:

Date,Title,URL,Description,Area,ContributionArea,Number of Projects,Visibility
28/03/2023,TEST,https://www.google.com,TEST,Microsoft Open Source Projects,Power Automate,1,Microsoft

MVPActivity -CSVPath data.csv
Error. Could not match name 'M' with HTMLFormStructure.
At C:\Program Files\WindowsPowerShell\Modules\SelMVP\1.0.2\Module.psm1:778 char:9
+         Throw ($LocalizedData.ErrorHTMLFormStructureMissingName -f $N ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error. Could no...LFormStructure.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error. Could not match name 'M' with HTMLFormStructure.

**Comment by ZanattaMichael** [comment]
Hey mate. I've gotten to the bottom of the issue; however, I'll need to create a new build this evening.

The issue pertains to the following lines of code within New-CSVFixture:

```
    # Get the CSV Column Names, excluding 'Area' & ContributionArea
    $CSVColumnNames = ($CSV | Get-Member).Name

    # Get the HTMLForm Structure and Get the Column Names Match from the CSV File
    $FormStructure = Get-HTMLFormStructure $CSV.Area[0] | Where-Object { $_.Name -in $CSVColumnNames }
```

`$CSV.Area[0]` is the bug here. So is `($CSV | Get-Member).Name`. I'll do some more testing tonight.

Thanks for raising this with me. I appreciate the patience.

**Comment by ZanattaMichael** [comment]
New version pushed. Issue should be resolved. Please note that's a 'single' area per csv. So if you have multiple entries in different areas, they will need to be separate CSV's.

**Comment by ZanattaMichael** [comment]
Don't forget to use update-module to get the newest module.
https://learn.microsoft.com/en-us/powershell/module/powershellget/update-module?view=powershell-7.3

**Comment by troystaylor** [comment]
@ZanattaMichael It works perfectly now. You've just saved me hours of watching that stupid form load.
