### ISSUE TITLE
Visibility set to 'Microsoft' seems to be ignored

### ISSUE THREAD

**Issue by flcdrg** [ZanattaMichael/SelMVP#70]
Setting Visibility to Microsoft is being ignored. I can see the UI showing the list, but it doesn't select Microsoft and leaves it as 'Everyone'

**Comment by ZanattaMichael** [comment]
Hi David,

Thanks for letting me know. Can you send me the module version and a code sample?

Thanks,

Michael.

Sent from my iPhone

On 11 Mar 2023, at 5:42 pm, David Gardiner ***@***.***> wrote:

﻿

Setting Visibility to Microsoft is being ignored. I can see the UI showing the list, but it doesn't select Microsoft and leaves it as 'Everyone'

**Comment by flcdrg** [comment]
`SelMVP\1.0.5\Module.psm1`

I'll see if I can repro the original problem.

This is possibly related - this code block actually errors:

```pwsh
MVPActivity "Twitter" {
    Area "Technical Social Media (Twitter, Facebook, LinkedIn...)"
    Visibility 'Microsoft'
    ContributionArea ".NET"
    Value "Date" "13/03/2023"
    Value "Title" "Twitter"
    Value "URL" "https://twitter.com/DavidRGardiner"
    Value "Description" "Personal Twitter account"
    Value "Number of Talks" 1
    Value "Number of Followers" 1
}
```

```
New-MVPActivity : Exception calling "Invoke" with "0" argument(s): "Exception calling "Click" with "0" argument(s):
"Element <li class="Item"> could not be scrolled into view""
At C:\Program Files\WindowsPowerShell\Modules\SelMVP\1.0.5\Module.psm1:2292 char:9
```

(I am in Australia, but yes the date format is fine - it gets converted to what the UI is happy with)

In this case, if I remove the `Visibility` line altogether, it submits it successfully.

**Comment by flcdrg** [comment]
This one reproduces the original problem for me though:

```powershell
MVPActivity "Test" {
    Area "Sample Code/Projects/Tools"
    Visibility 'Microsoft'
    ContributionArea "Visual Studio Extensibility"
    Value "Date" "13/03/2023"
    Value "Title" "Test"
    Value "URL" "https://marketplace.visualstudio.com"
    Value "Description" "Example"
    Value "Number of Samples" 1
    Value "Number of Downloads" 1
}
```

The activity is added, but visibility is set to 'Everyone'

**Comment by ZanattaMichael** [comment]
No worries. I'm AUS based as well. :-p Out of curiosity what driver/browser are you using?

**Comment by flcdrg** [comment]
Firefox and geckodriver-v0.32.2-win64

**Comment by ZanattaMichael** [comment]
Thanks for that. I'm investigating now.

**Comment by ZanattaMichael** [comment]
I've gotten to the bottom of the issue. The JavaScript isn't catching up to the click event, causing the event to fail. I've refactored the cmdlet and wrapped the logic within looping try/catch (ttry). I need to do some more testing, however I will release a new version tomorrow.

**Comment by ZanattaMichael** [comment]
New version is out. Please confirm the issue has been fixed on your end.

https://www.powershellgallery.com/packages/SelMVP/1.0.6

**Comment by flcdrg** [comment]
Thanks. I've done most of my activities, but if I think of any more I'll try it out.
